# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Image.destroy_all
Review.destroy_all
BusinessCategory.destroy_all
BusinessHour.destroy_all
Business.destroy_all
User.destroy_all

categories = "Active Life (active)
ATV Rentals/Tours (atvrentals)
Airsoft (airsoft)
Amateur Sports Teams (amateursportsteams)
Amusement Parks (amusementparks)
Aquariums (aquariums)
Archery (archery)
Axe Throwing (axethrowing)
Badminton (badminton)
Baseball Fields (baseballfields)
Basketball Courts (basketballcourts)
Batting Cages (battingcages)
Beach Equipment Rentals (beachequipmentrental)
Beaches (beaches)
Bike Parking (bikeparking)
Bike Rentals (bikerentals)
Boating (boating)
Bobsledding (bobsledding)
Bocce Ball (bocceball)
Bowling (bowling)
Bubble Soccer (bubblesoccer)
Bungee Jumping (bungeejumping)
Carousels (carousels)
Challenge Courses (challengecourses)
Climbing (climbing)
Cycling Classes (cyclingclasses)
Day Camps (daycamps)
Disc Golf (discgolf)
Diving (diving)
Free Diving (freediving)
Scuba Diving (scuba)
Escape Games (escapegames)
Fencing Clubs (fencing)
Fishing (fishing)
Fitness & Instruction (fitness)
Aerial Fitness (aerialfitness)
Barre Classes (barreclasses)
Boot Camps (bootcamps)
Boxing (boxing)
Cardio Classes (cardioclasses)
Dance Studios (dancestudio)
Golf Lessons (golflessons)
Gyms (gyms)
Circuit Training Gyms (circuittraininggyms)
Interval Training Gyms (intervaltraininggyms)
Martial Arts (martialarts)
Brazilian Jiu-jitsu (brazilianjiujitsu)
Chinese Martial Arts (chinesemartialarts)
Karate (karate)
Kickboxing (kickboxing)
Muay Thai (muaythai)
Taekwondo (taekwondo)
Meditation Centers (meditationcenters)
Pilates (pilates)
Qi Gong (qigong)
Self-defense Classes (selfdefenseclasses)
Swimming Lessons/Schools (swimminglessons)
Tai Chi (taichi)
Trainers (healthtrainers)
Yoga (yoga)
Flyboarding (flyboarding)
Go Karts (gokarts)
Golf (golf)
Gun/Rifle Ranges (gun_ranges)
Gymnastics (gymnastics)
Hang Gliding (hanggliding)
Hiking (hiking)
Horse Racing (horseracing)
Horseback Riding (horsebackriding)
Hot Air Balloons (hot_air_balloons)
Indoor Playcentre (indoor_playcenter)
Jet Skis (jetskis)
Kids Activities (kids_activities)
Kiteboarding (kiteboarding)
Lakes (lakes)
Laser Tag (lasertag)
Mini Golf (mini_golf)
Mountain Biking (mountainbiking)
Nudist (nudist)
Paddleboarding (paddleboarding)
Paintball (paintball)
Parasailing (parasailing)
Parks (parks)
Dog Parks (dog_parks)
Skate Parks (skate_parks)
Playgrounds (playgrounds)
Races & Competitions (races)
Racing Experience (racingexperience)
Rafting/Kayaking (rafting)
Recreation Centers (recreation)
Rock Climbing (rock_climbing)
Sailing (sailing)
Scavenger Hunts (scavengerhunts)
Scooter Rentals (scooterrentals)
Senior Centers (seniorcenters)
Skating Rinks (skatingrinks)
Skydiving (skydiving)
Sledding (sledding)
Snorkeling (snorkeling)
Soccer (football)
Sports Clubs (sports_clubs)
Squash (squash)
Summer Camps (summer_camps)
Surfing (surfing)
Swimming Pools (swimmingpools)
Tennis (tennis)
Trampoline Parks (trampoline)
Tubing (tubing)
Water Parks (waterparks)
Wildlife Hunting Ranges (wildlifehunting)
Ziplining (zipline)
Zoos (zoos)
Petting Zoos (pettingzoos)
Zorbing (zorbing)
Arts & Entertainment (arts)
Arcades (arcades)
Art Galleries (galleries)
Bingo Halls (bingo)
Botanical Gardens (gardens)
Cabaret (cabaret)
Casinos (casinos)
Cinema (movietheaters)
Drive-In Theater (driveintheater)
Outdoor Movies (outdoormovies)
Country Clubs (countryclubs)
Cultural Center (culturalcenter)
Eatertainment (eatertainment)
Farms (farms)
Attraction Farms (attractionfarms)
Pick Your Own Farms (pickyourown)
Ranches (ranches)
Festivals (festivals)
Haunted Houses (hauntedhouses)
Jazz & Blues (jazzandblues)
LAN Centers (lancenters)
Makerspaces (makerspaces)
Museums (museums)
Art Museums (artmuseums)
Children's Museums (childrensmuseums)
Music Venues (musicvenues)
Observatories (observatories)
Opera & Ballet (opera)
Paint & Sip (paintandsip)
Performing Arts (theater)
Planetarium (planetarium)
Professional Sports Teams (sportsteams)
Race Tracks (racetracks)
Rodeo (rodeo)
Social Clubs (social_clubs)
Veterans Organizations (veteransorganizations)
Stadiums & Arenas (stadiumsarenas)
Studio Taping (studiotaping)
Supernatural Readings (psychic_astrology)
Astrologers (astrologers)
Mystics (mystics)
Psychic Mediums (psychicmediums)
Psychics (psychics)
Ticket Sales (ticketsales)
Virtual Reality Centers (virtualrealitycenters)
Wineries (wineries)
Wine Tasting Room (winetastingroom)
Automotive (auto)
Aircraft Dealers (aircraftdealers)
Aircraft Repairs (aircraftrepairs)
Auto Customization (autocustomization)
Auto Detailing (auto_detailing)
Auto Glass Services (autoglass)
Car Window Tinting (carwindowtinting)
Auto Loan Providers (autoloanproviders)
Auto Parts & Supplies (autopartssupplies)
Auto Repair (autorepair)
DIY Auto Shop (diyautoshop)
Auto Security (autosecurity)
Auto Upholstery (autoupholstery)
Aviation Services (aviationservices)
Boat Dealers (boatdealers)
Boat Parts & Supplies (boatpartsandsupplies)
Body Shops (bodyshops)
Car Auctions (carauctions)
Car Brokers (carbrokers)
Car Buyers (carbuyers)
Car Dealers (car_dealers)
Car Inspectors (autodamageassessment)
Car Share Services (carshares)
Car Stereo Installation (stereo_installation)
Car Wash (carwash)
Commercial Truck Dealers (truckdealers)
Commercial Truck Repair (truckrepair)
EV Charging Stations (evchargingstations)
Fuel Docks (fueldocks)
Gas Stations (servicestations)
Golf Cart Dealers (golfcartdealers)
Hybrid Car Repair (hybridcarrepair)
Interlock Systems (interlocksystems)
Marinas (marinas)
Mobile Dent Repair (mobiledentrepair)
Mobility Equipment Sales & Services (mobilityequipment)
Motorcycle Dealers (motorcycledealers)
Motorcycle Repair (motorcyclerepair)
Motorsport Vehicle Dealers (motodealers)
Motorsport Vehicle Repairs (motorepairs)
Oil Change Stations (oilchange)
Parking (parking)
RV Dealers (rv_dealers)
RV Repair (rvrepair)
Registration Services (registrationservices)
Roadside Assistance (roadsideassist)
Service Stations (service_stations)
Smog Check Stations (smog_check_stations)
Tires (tires)
Towing (towing)
Trailer Dealers (trailerdealers)
Trailer Rental (trailerrental)
Trailer Repair (trailerrepair)
Transmission Repair (transmissionrepair)
Truck Rental (truck_rental)
Used Car Dealers (usedcardealers)
Vehicle Shipping (vehicleshipping)
Vehicle Wraps (vehiclewraps)
Wheel & Rim Repair (wheelrimrepair)
Windshield Installation & Repair (windshieldinstallrepair)
Beauty & Spas (beautysvc)
Acne Treatment (acnetreatment)
Barbers (barbers)
Cosmetics & Beauty Supply (cosmetics)
Day Spas (spas)
Eyebrow Services (eyebrowservices)
Eyelash Service (eyelashservice)
Hair Extensions (hair_extensions)
Hair Loss Centers (hairloss)
Hair Removal (hairremoval)
Laser Hair Removal (laser_hair_removal)
Sugaring (sugaring)
Threading Services (threadingservices)
Waxing (waxing)
Hair Salons (hair)
Blow Dry/Out Services (blowoutservices)
Hair Extensions (hair_extensions)
Hair Stylists (hairstylists)
Kids Hair Salons (kidshairsalons)
Men's Hair Salons (menshair)
Hot Springs (hotsprings)
Makeup Artists (makeupartists)
Massage (massage)
Medical Spas (medicalspa)
Aestheticians (aestheticians)
Nail Salons (othersalons)
Nail Technicians (nailtechnicians)
Perfume (perfume)
Permanent Makeup (permanentmakeup)
Piercing (piercing)
Skin Care (skincare)
Estheticians (estheticians)
Tanning (tanning)
Spray Tanning (spraytanning)
Tanning Beds (tanningbeds)
Tattoo (tattoo)
Teeth Whitening (teethwhitening)
Education (education)
Adult Education (adultedu)
Art Classes (artclasses)
Glass Blowing (glassblowing)
College Counseling (collegecounseling)
Colleges & Universities (collegeuniv)
Educational Services (educationservices)
Elementary Schools (elementaryschools)
Middle Schools & High Schools (highschools)
Montessori Schools (montessori)
Preschools (preschools)
Private Schools (privateschools)
Private Tutors (privatetutors)
Religious Schools (religiousschools)
Special Education (specialed)
Specialty Schools (specialtyschools)
Art Schools (artschools)
Bartending Schools (bartendingschools)
CPR Classes (cprclasses)
Cheerleading (cheerleading)
Childbirth Education (childbirthedu)
Cooking Schools (cookingschools)
Cosmetology Schools (cosmetology_schools)
DUI Schools (duischools)
Dance Schools (dance_schools)
Drama Schools (dramaschools)
Driving Schools (driving_schools)
Firearm Training (firearmtraining)
First Aid Classes (firstaidclasses)
Flight Instruction (flightinstruction)
Food Safety Training (foodsafety)
Language Schools (language_schools)
Massage Schools (massage_schools)
Nursing Schools (nursingschools)
Parenting Classes (parentingclasses)
Photography Classes (photoclasses)
Pole Dancing Classes (poledancingclasses)
Ski Schools (skischools)
Speech Training (speechtraining)
Surf Schools (surfschools)
Swimming Lessons/Schools (swimminglessons)
Traffic Schools (trafficschools)
Vocational & Technical School (vocation)
Tasting Classes (tastingclasses)
Cheese Tasting Classes (cheesetastingclasses)
Wine Tasting Classes (winetasteclasses)
Test Preparation (testprep)
Tutoring Centers (tutoring)
Waldorf Schools (waldorfschools)
Event Planning & Services (eventservices)
Balloon Services (balloonservices)
Bartenders (bartenders)
Boat Charters (boatcharters)
Cards & Stationery (stationery)
Caricatures (caricatures)
Caterers (catering)
Clowns (clowns)
DJs (djs)
Face Painting (facepainting)
Floral Designers (floraldesigners)
Game Truck Rental (gametruckrental)
Golf Cart Rentals (golfcartrentals)
Henna Artists (hennaartists)
Hotels (hotels)
Mountain Huts (mountainhuts)
Rest Stops (reststops)
Magicians (magicians)
Mohels (mohels)
Musicians (musicians)
Officiants (officiants)
Party & Event Planning (eventplanning)
Party Bike Rentals (partybikerentals)
Party Bus Rentals (partybusrentals)
Party Characters (partycharacters)
Party Equipment Rentals (partyequipmentrentals)
Audio/Visual Equipment Rental (audiovisualequipmentrental)
Bounce House Rentals (bouncehouserentals)
Karaoke Rental (karaokerental)
Party Supplies (partysupplies)
Personal Chefs (personalchefs)
Photo Booth Rentals (photoboothrentals)
Photographers (photographers)
Boudoir Photography (boudoirphotography)
Event Photography (eventphotography)
Session Photography (sessionphotography)
Silent Disco (silentdisco)
Sommelier Services (sommelierservices)
Team Building Activities (teambuilding)
Trivia Hosts (triviahosts)
Valet Services (valetservices)
Venues & Event Spaces (venues)
Videographers (videographers)
Wedding Chapels (weddingchappels)
Wedding Planning (wedding_planning)
Financial Services (financialservices)
Banks & Credit Unions (banks)
Business Financing (businessfinancing)
Check Cashing/Pay-day Loans (paydayloans)
Currency Exchange (currencyexchange)
Debt Relief Services (debtrelief)
Financial Advising (financialadvising)
Installment Loans (installmentloans)
Insurance (insurance)
Auto Insurance (autoinsurance)
Home & Rental Insurance (homeinsurance)
Life Insurance (lifeinsurance)
Investing (investing)
Mortgage Lenders (mortgagelenders)
Tax Services (taxservices)
Title Loans (titleloans)
Food (food)
Acai Bowls (acaibowls)
Bagels (bagels)
Bakeries (bakeries)
Beer, Wine & Spirits (beer_and_wine)
Beverage Store (beverage_stores)
Breweries (breweries)
Brewpubs (brewpubs)
Bubble Tea (bubbletea)
Butcher (butcher)
CSA (csa)
Chimney Cakes (chimneycakes)
Cideries (cideries)
Coffee & Tea (coffee)
Coffee Roasteries (coffeeroasteries)
Convenience Stores (convenience)
Cupcakes (cupcakes)
Custom Cakes (customcakes)
Desserts (desserts)
Distilleries (distilleries)
Do-It-Yourself Food (diyfood)
Donuts (donuts)
Empanadas (empanadas)
Farmers Market (farmersmarket)
Food Delivery Services (fooddeliveryservices)
Food Trucks (foodtrucks)
Gelato (gelato)
Grocery (grocery)
Honey (honey)
Ice Cream & Frozen Yogurt (icecream)
Imported Food (importedfood)
International Grocery (intlgrocery)
Internet Cafes (internetcafe)
Juice Bars & Smoothies (juicebars)
Kombucha (kombucha)
Organic Stores (organic_stores)
Patisserie/Cake Shop (cakeshop)
Piadina (piadina)
Poke (poke)
Pretzels (pretzels)
Shaved Ice (shavedice)
Shaved Snow (shavedsnow)
Smokehouse (smokehouse)
Specialty Food (gourmet)
Candy Stores (candy)
Cheese Shops (cheese)
Chocolatiers & Shops (chocolate)
Fruits & Veggies (markets)
Health Markets (healthmarkets)
Herbs & Spices (herbsandspices)
Macarons (macarons)
Meat Shops (meats)
Olive Oil (oliveoil)
Pasta Shops (pastashops)
Popcorn Shops (popcorn)
Seafood Markets (seafoodmarkets)
Street Vendors (streetvendors)
Tea Rooms (tea)
Water Stores (waterstores)
Wineries (wineries)
Wine Tasting Room (winetastingroom)
Health & Medical (health)
Acupuncture (acupuncture)
Alternative Medicine (alternativemedicine)
Animal Assisted Therapy (animalassistedtherapy)
Assisted Living Facilities (assistedliving)
Ayurveda (ayurveda)
Behavior Analysts (behavioranalysts)
Blood & Plasma Donation Centers (blooddonation)
Body Contouring (bodycontouring)
Cannabis Clinics (cannabis_clinics)
Cannabis Tours (cannabistours)
Cannabis Collective (cannabiscollective)
Chiropractors (chiropractors)
Colonics (colonics)
Concierge Medicine (conciergemedicine)
Counseling & Mental Health (c_and_mh)
Psychologists (psychologists)
Sex Therapists (sextherapists)
Sports Psychologists (sportspsychologists)
Cryotherapy (cryotherapy)
Dental Hygienists (dentalhygienists)
Dentists (dentists)
Cosmetic Dentists (cosmeticdentists)
Endodontists (endodontists)
General Dentistry (generaldentistry)
Oral Surgeons (oralsurgeons)
Orthodontists (orthodontists)
Pediatric Dentists (pediatric_dentists)
Periodontists (periodontists)
Diagnostic Services (diagnosticservices)
Diagnostic Imaging (diagnosticimaging)
Laboratory Testing (laboratorytesting)
Dialysis Clinics (dialysisclinics)
Dietitians (dietitians)
Doctors (physicians)
Addiction Medicine (addictionmedicine)
Allergists (allergist)
Anesthesiologists (anesthesiologists)
Audiologist (audiologist)
Cardiologists (cardiology)
Cosmetic Surgeons (cosmeticsurgeons)
Dermatologists (dermatology)
Ear Nose & Throat (earnosethroat)
Emergency Medicine (emergencymedicine)
Endocrinologists (endocrinologists)
Family Practice (familydr)
Fertility (fertility)
Gastroenterologist (gastroenterologist)
Geneticists (geneticists)
Gerontologists (gerontologist)
Hepatologists (hepatologists)
Hospitalists (hospitalists)
Immunodermatologists (immunodermatologists)
Infectious Disease Specialists (infectiousdisease)
Internal Medicine (internalmed)
Naturopathic/Holistic (naturopathic)
Nephrologists (nephrologists)
Neurologist (neurologist)
Neuropathologists (neuropathologists)
Neurotologists (neurotologists)
Obstetricians & Gynecologists (obgyn)
Oncologist (oncologist)
Ophthalmologists (opthamalogists)
Retina Specialists (retinaspecialists)
Orthopedists (orthopedists)
Osteopathic Physicians (osteopathicphysicians)
Otologists (otologists)
Pain Management (painmanagement)
Pathologists (pathologists)
Pediatricians (pediatricians)
Phlebologists (phlebologists)
Plastic Surgeons (plasticsurgeons)
Podiatrists (podiatrists)
Preventive Medicine (preventivemedicine)
Proctologists (proctologist)
Psychiatrists (psychiatrists)
Pulmonologist (pulmonologist)
Radiologists (radiologists)
Rheumatologists (rhematologists)
Spine Surgeons (spinesurgeons)
Sports Medicine (sportsmed)
Surgeons (surgeons)
Tattoo Removal (tattooremoval)
Toxicologists (toxicologists)
Undersea/Hyperbaric Medicine (underseamedicine)
Urologists (urologists)
Vascular Medicine (vascularmedicine)
Doulas (doulas)
Emergency Rooms (emergencyrooms)
Float Spa (floatspa)
Habilitative Services (habilitativeservices)
Halfway Houses (halfwayhouses)
Halotherapy (halotherapy)
Health Coach (healthcoach)
Health Insurance Offices (healthinsurance)
Hearing Aid Providers (hearingaidproviders)
Herbal Shops (herbalshops)
Home Health Care (homehealthcare)
Hospice (hospice)
Hospitals (hospitals)
Hydrotherapy (hydrotherapy)
Hypnosis/Hypnotherapy (hypnosis)
IV Hydration (ivhydration)
Lactation Services (lactationservices)
Laser Eye Surgery/Lasik (laserlasikeyes)
Lice Services (liceservices)
Massage Therapy (massage_therapy)
Medical Cannabis Referrals (cannabisreferrals)
Medical Centers (medcenters)
Walk-in Clinics (walkinclinics)
Medical Spas (medicalspa)
Aestheticians (aestheticians)
Medical Transportation (medicaltransportation)
Memory Care (memorycare)
Midwives (midwives)
Nurse Practitioner (nursepractitioner)
Nutritionists (nutritionists)
Occupational Therapy (occupationaltherapy)
Optometrists (optometrists)
Organ & Tissue Donor Services (organdonorservices)
Orthotics (orthotics)
Oxygen Bars (oxygenbars)
Personal Care Services (personalcare)
Pharmacy (pharmacy)
Physical Therapy (physicaltherapy)
Placenta Encapsulations (placentaencapsulation)
Prenatal/Perinatal Care (prenatal)
Prosthetics (prosthetics)
Prosthodontists (prosthodontists)
Reflexology (reflexology)
Rehabilitation Center (rehabilitation_center)
Reiki (reiki)
Retirement Homes (retirement_homes)
Saunas (saunas)
Skilled Nursing (skillednursing)
Sleep Specialists (sleepspecialists)
Speech Therapists (speech_therapists)
Sperm Clinic (spermclinic)
Traditional Chinese Medicine (tcm)
Tui Na (tuina)
Ultrasound Imaging Centers (ultrasoundimagingcenters)
Urgent Care (urgent_care)
Weight Loss Centers (weightlosscenters)
Home Services (homeservices)
Artificial Turf (artificialturf)
Building Supplies (buildingsupplies)
Cabinetry (cabinetry)
Carpenters (carpenters)
Carpet Installation (carpetinstallation)
Carpeting (carpeting)
Childproofing (childproofing)
Chimney Sweeps (chimneysweeps)
Contractors (contractors)
Countertop Installation (countertopinstall)
Damage Restoration (damagerestoration)
Decks & Railing (decksrailing)
Demolition Services (demolitionservices)
Door Sales/Installation (doorsales)
Drywall Installation & Repair (drywall)
Electricians (electricians)
Excavation Services (excavationservices)
Fences & Gates (fencesgates)
Fire Protection Services (fireprotection)
Fireplace Services (fireplace)
Firewood (firewood)
Flooring (flooring)
Foundation Repair (foundationrepair)
Furniture Assembly (furnitureassembly)
Garage Door Services (garage_door_services)
Gardeners (gardeners)
Glass & Mirrors (glassandmirrors)
Grout Services (groutservices)
Gutter Services (gutterservices)
Handyman (handyman)
Heating & Air Conditioning/HVAC (hvac)
Holiday Decorating Services (seasonaldecorservices)
Home Automation (homeautomation)
Home Cleaning (homecleaning)
Home Energy Auditors (homeenergyauditors)
Home Inspectors (home_inspectors)
Home Network Installation (homenetworkinstall)
Home Organization (home_organization)
Home Theatre Installation (hometheatreinstallation)
Home Window Tinting (homewindowtinting)
House Sitters (housesitters)
Insulation Installation (insulationinstallation)
Interior Design (interiordesign)
Internet Service Providers (isps)
Irrigation (irrigation)
Keys & Locksmiths (locksmiths)
Landscape Architects (landscapearchitects)
Landscaping (landscaping)
Lawn Services (lawnservices)
Lighting Fixtures & Equipment (lighting)
Masonry/Concrete (masonry_concrete)
Mobile Home Repair (mobile_home_repair)
Movers (movers)
Packing Services (packingservices)
Painters (painters)
Patio Coverings (patiocoverings)
Plumbing (plumbing)
Backflow Services (backflowservices)
Pool & Hot Tub Service (poolservice)
Pool Cleaners (poolcleaners)
Pressure Washers (pressurewashers)
Real Estate (realestate)
Apartments (apartments)
Art Space Rentals (artspacerentals)
Commercial Real Estate (commercialrealestate)
Condominiums (condominiums)
Estate Liquidation (estateliquidation)
Home Developers (homedevelopers)
Home Staging (homestaging)
Homeowner Association (homeownerassociation)
Housing Cooperatives (housingcooperatives)
Kitchen Incubators (kitchenincubators)
Mobile Home Dealers (mobilehomes)
Mobile Home Parks (mobileparks)
Mortgage Brokers (mortgagebrokers)
Property Management (propertymgmt)
Real Estate Agents (realestateagents)
Apartment Agents (apartmentagents)
Real Estate Services (realestatesvcs)
Land Surveying (landsurveying)
Real Estate Photography (estatephotography)
Shared Office Spaces (sharedofficespaces)
University Housing (university_housing)
Refinishing Services (refinishing)
Roof Inspectors (roofinspectors)
Roofing (roofing)
Security Systems (securitysystems)
Shades & Blinds (blinds)
Shutters (shutters)
Siding (vinylsiding)
Solar Installation (solarinstallation)
Solar Panel Cleaning (solarpanelcleaning)
Structural Engineers (structuralengineers)
Stucco Services (stucco)
Television Service Providers (televisionserviceproviders)
Tiling (tiling)
Tree Services (treeservices)
Utilities (utilities)
Electricity Suppliers (electricitysuppliers)
Natural Gas Suppliers (naturalgassuppliers)
Water Suppliers (watersuppliers)
Wallpapering (wallpapering)
Water Heater Installation/Repair (waterheaterinstallrepair)
Water Purification Services (waterpurification)
Waterproofing (waterproofing)
Window Washing (windowwashing)
Windows Installation (windowsinstallation)
Hotels & Travel (hotelstravel)
Airports (airports)
Airport Terminals (airportterminals)
Bed & Breakfast (bedbreakfast)
Campgrounds (campgrounds)
Car Rental (carrental)
Guest Houses (guesthouses)
Health Retreats (healthretreats)
Hostels (hostels)
Hotels (hotels)
Mountain Huts (mountainhuts)
Rest Stops (reststops)
Motorcycle Rental (motorcycle_rental)
RV Parks (rvparks)
RV Rental (rvrental)
Resorts (resorts)
Ski Resorts (skiresorts)
Tours (tours)
Aerial Tours (aerialtours)
Architectural Tours (architecturaltours)
Art Tours (arttours)
Beer Tours (beertours)
Bike tours (biketours)
Boat Tours (boattours)
Bus Tours (bustours)
Food Tours (foodtours)
Historical Tours (historicaltours)
Scooter Tours (scootertours)
Walking Tours (walkingtours)
Whale Watching Tours (whalewatchingtours)
Wine Tours (winetours)
Train Stations (trainstations)
Transportation (transport)
Airlines (airlines)
Airport Shuttles (airport_shuttles)
Bike Sharing (bikesharing)
Bus Stations (busstations)
Buses (buses)
Cable Cars (cablecars)
Ferries (ferries)
Limos (limos)
Metro Stations (metrostations)
Pedicabs (pedicabs)
Private Jet Charter (privatejetcharter)
Public Transportation (publictransport)
Taxis (taxis)
Town Car Service (towncarservice)
Trains (trains)
Travel Services (travelservices)
Luggage Storage (luggagestorage)
Passport & Visa Services (passportvisaservices)
Travel Agents (travelagents)
Visitor Centers (visitorcenters)
Vacation Rental Agents (vacationrentalagents)
Vacation Rentals (vacation_rentals)
Local Flavor (localflavor)
Parklets (parklets)
Public Art (publicart)
Unofficial Yelp Events (unofficialyelpevents)
Yelp Events (yelpevents)
Local Services (localservices)
3D Printing (3dprinting)
Adoption Services (adoptionservices)
Air Duct Cleaning (airductcleaning)
Appliances & Repair (homeappliancerepair)
Appraisal Services (appraisalservices)
Art Restoration (artrestoration)
Awnings (awnings)
Bail Bondsmen (bailbondsmen)
Bike Repair/Maintenance (bike_repair_maintenance)
Bookbinding (bookbinding)
Bus Rental (busrental)
Calligraphy (calligraphy)
Carpet Cleaning (carpet_cleaning)
Carpet Dyeing (carpetdyeing)
Child Care & Day Care (childcare)
Clock Repair (clockrepair)
Community Book Box (communitybookbox)
Community Gardens (communitygardens)
Community Service/Non-Profit (nonprofit)
Food Banks (foodbanks)
Homeless Shelters (homelessshelters)
Couriers & Delivery Services (couriers)
Crane Services (craneservices)
Donation Center (donationcenter)
Elder Care Planning (eldercareplanning)
Electronics Repair (electronicsrepair)
Engraving (engraving)
Environmental Abatement (enviroabatement)
Environmental Testing (environmentaltesting)
Farm Equipment Repair (farmequipmentrepair)
Fingerprinting (fingerprinting)
Funeral Services & Cemeteries (funeralservices)
Cremation Services (cremationservices)
Mortuary Services (mortuaryservices)
Furniture Rental (rentfurniture)
Furniture Repair (furniturerepair)
Furniture Reupholstery (reupholstery)
Generator Installation/Repair (generatorinstallrepair)
Gunsmith (gunsmith)
Hazardous Waste Disposal (hazardouswastedisposal)
Hydro-jetting (hydrojetting)
IT Services & Computer Repair (itservices)
Data Recovery (datarecovery)
Mobile Phone Repair (mobilephonerepair)
Telecommunications (telecommunications)
Ice Delivery (icedelivery)
Jewelry Repair (jewelryrepair)
Junk Removal & Hauling (junkremovalandhauling)
Dumpster Rental (dumpsterrental)
Junkyards (junkyards)
Knife Sharpening (knifesharpening)
Laundry Services (laundryservices)
Dry Cleaning (dryclean)
Laundromat (laundromat)
Machine & Tool Rental (machinerental)
Machine Shops (machineshops)
Mailbox Centers (mailboxcenters)
Metal Detector Services (metaldetectorservices)
Metal Fabricators (metalfabricators)
Misting System Services (mistingsystemservices)
Musical Instrument Services (musicinstrumentservices)
Guitar Stores (guitarstores)
Piano Services (pianoservices)
Piano Stores (pianostores)
Vocal Coach (vocalcoach)
Nanny Services (nannys)
Notaries (notaries)
Pest Control (pest_control)
Powder Coating (powdercoating)
Printing Services (copyshops)
Propane (propane)
Recording & Rehearsal Studios (recording_studios)
Recycling Center (recyclingcenter)
Sandblasting (sandblasting)
Screen Printing (screenprinting)
Screen Printing/T-Shirt Printing (screen_printing_tshirt_printing)
Self Storage (selfstorage)
Septic Services (septicservices)
Sewing & Alterations (sewingalterations)
Shipping Centers (shipping_centers)
Shoe Repair (shoerepair)
Shoe Shine (shoeshine)
Snow Removal (snowremoval)
Snuggle Services (snuggleservices)
TV Mounting (tvmounting)
Watch Repair (watch_repair)
Water Delivery (waterdelivery)
Well Drilling (welldrilling)
Wildlife Control (wildlifecontrol)
Mass Media (massmedia)
Print Media (printmedia)
Radio Stations (radiostations)
Television Stations (televisionstations)
Nightlife (nightlife)
Adult Entertainment (adultentertainment)
Strip Clubs (stripclubs)
Striptease Dancers (stripteasedancers)
Bar Crawl (barcrawl)
Bars (bars)
Airport Lounges (airportlounges)
Beer Bar (beerbar)
Champagne Bars (champagne_bars)
Cigar Bars (cigarbars)
Cocktail Bars (cocktailbars)
Dive Bars (divebars)
Drive-Thru Bars (drivethrubars)
Gay Bars (gaybars)
Hookah Bars (hookah_bars)
Irish Pub (irish_pubs)
Lounges (lounges)
Pubs (pubs)
Speakeasies (speakeasies)
Sports Bars (sportsbars)
Tiki Bars (tikibars)
Vermouth Bars (vermouthbars)
Whiskey Bars (whiskeybars)
Wine Bars (wine_bars)
Beer Gardens (beergardens)
Club Crawl (clubcrawl)
Comedy Clubs (comedyclubs)
Country Dance Halls (countrydancehalls)
Dance Clubs (danceclubs)
Jazz & Blues (jazzandblues)
Karaoke (karaoke)
Music Venues (musicvenues)
Piano Bars (pianobars)
Pool Halls (poolhalls)
Pets (pets)
Animal Shelters (animalshelters)
Horse Boarding (horse_boarding)
Pet Adoption (petadoption)
Pet Services (petservices)
Animal Physical Therapy (animalphysicaltherapy)
Aquarium Services (aquariumservices)
Dog Walkers (dogwalkers)
Emergency Pet Hospital (emergencypethospital)
Farriers (farriers)
Holistic Animal Care (animalholistic)
Pet Breeders (petbreeders)
Pet Cremation Services (petcremation)
Pet Groomers (groomer)
Pet Hospice (pethospice)
Pet Insurance (petinsurance)
Pet Photography (petphotography)
Pet Sitting (pet_sitting)
Pet Boarding (petboarding)
Pet Training (pet_training)
Pet Transportation (pettransport)
Pet Waste Removal (petwasteremoval)
Pet Stores (petstore)
Bird Shops (birdshops)
Local Fish Stores (localfishstores)
Reptile Shops (reptileshops)
Veterinarians (vet)
Professional Services (professional)
Accountants (accountants)
Advertising (advertising)
Architects (architects)
Billing Services (billingservices)
Boat Repair (boatrepair)
Bookkeepers (bookkeepers)
Business Consulting (businessconsulting)
Career Counseling (careercounseling)
Commissioned Artists (commissionedartists)
Customs Brokers (customsbrokers)
Digitizing Services (digitizingservices)
Duplication Services (duplicationservices)
Editorial Services (editorialservices)
Employment Agencies (employmentagencies)
Feng Shui (fengshui)
Graphic Design (graphicdesign)
Indoor Landscaping (indoorlandscaping)
Internet Service Providers (isps)
Lawyers (lawyers)
Bankruptcy Law (bankruptcy)
Business Law (businesslawyers)
Contract Law (contractlaw)
Criminal Defense Law (criminaldefense)
DUI Law (duilawyers)
Disability Law (disabilitylaw)
Divorce & Family Law (divorce)
Employment Law (employmentlawyers)
Entertainment Law (entertainmentlaw)
Estate Planning Law (estateplanning)
Wills, Trusts, & Probates (willstrustsprobates)
General Litigation (general_litigation)
IP & Internet Law (iplaw)
Immigration Law (immigrationlawyers)
Medical Law (medicallaw)
Personal Injury Law (personal_injury)
Real Estate Law (realestatelawyers)
Social Security Law (socialsecuritylaw)
Tax Law (taxlaw)
Traffic Ticketing Law (trafficticketinglaw)
Workers Compensation Law (workerscomplaw)
Legal Services (legalservices)
Court Reporters (courtreporters)
Process Servers (processservers)
Life Coach (lifecoach)
Marketing (marketing)
Matchmakers (matchmakers)
Mediators (mediators)
Music Production Services (musicproduction)
Office Cleaning (officecleaning)
Patent Law (patentlaw)
Payroll Services (payroll)
Personal Assistants (personalassistants)
Private Investigation (privateinvestigation)
Product Design (productdesign)
Public Adjusters (publicadjusters)
Public Relations (publicrelations)
Security Services (security)
Shredding Services (shredding)
Signmaking (signmaking)
Software Development (softwaredevelopment)
Talent Agencies (talentagencies)
Taxidermy (taxidermy)
Tenant and Eviction Law (tenantlaw)
Translation Services (translationservices)
Video/Film Production (videofilmproductions)
Web Design (web_design)
Wholesalers (wholesalers)
Restaurant Supplies (suppliesrestaurant)
Public Services & Government (publicservicesgovt)
Civic Center (civiccenter)
Community Centers (communitycenters)
Courthouses (courthouses)
Departments of Motor Vehicles (departmentsofmotorvehicles)
Embassy (embassy)
Fire Departments (firedepartments)
Jails & Prisons (jailsandprisons)
Landmarks & Historical Buildings (landmarks)
Libraries (libraries)
Municipality (municipality)
Police Departments (policedepartments)
Post Offices (postoffices)
Town Hall (townhall)
Real Estate (realestate)
Apartments (apartments)
Art Space Rentals (artspacerentals)
Commercial Real Estate (commercialrealestate)
Condominiums (condominiums)
Estate Liquidation (estateliquidation)
Home Developers (homedevelopers)
Home Staging (homestaging)
Homeowner Association (homeownerassociation)
Housing Cooperatives (housingcooperatives)
Kitchen Incubators (kitchenincubators)
Mobile Home Dealers (mobilehomes)
Mobile Home Parks (mobileparks)
Mortgage Brokers (mortgagebrokers)
Property Management (propertymgmt)
Real Estate Agents (realestateagents)
Apartment Agents (apartmentagents)
Real Estate Services (realestatesvcs)
Land Surveying (landsurveying)
Real Estate Photography (estatephotography)
Shared Office Spaces (sharedofficespaces)
University Housing (university_housing)
Religious Organizations (religiousorgs)
Buddhist Temples (buddhist_temples)
Churches (churches)
Hindu Temples (hindu_temples)
Mosques (mosques)
Sikh Temples (sikhtemples)
Synagogues (synagogues)
Restaurants (restaurants)
Afghan (afghani)
African (african)
Senegalese (senegalese)
South African (southafrican)
American (New) (newamerican)
American (Traditional) (tradamerican)
Arabian (arabian)
Argentine (argentine)
Armenian (armenian)
Asian Fusion (asianfusion)
Australian (australian)
Austrian (austrian)
Bangladeshi (bangladeshi)
Barbeque (bbq)
Basque (basque)
Belgian (belgian)
Brasseries (brasseries)
Brazilian (brazilian)
Breakfast & Brunch (breakfast_brunch)
British (british)
Buffets (buffets)
Bulgarian (bulgarian)
Burgers (burgers)
Burmese (burmese)
Cafes (cafes)
Themed Cafes (themedcafes)
Cafeteria (cafeteria)
Cajun/Creole (cajun)
Cambodian (cambodian)
Caribbean (caribbean)
Dominican (dominican)
Haitian (haitian)
Puerto Rican (puertorican)
Trinidadian (trinidadian)
Catalan (catalan)
Cheesesteaks (cheesesteaks)
Chicken Shop (chickenshop)
Chicken Wings (chicken_wings)
Chinese (chinese)
Cantonese (cantonese)
Dim Sum (dimsum)
Hainan (hainan)
Shanghainese (shanghainese)
Szechuan (szechuan)
Comfort Food (comfortfood)
Creperies (creperies)
Cuban (cuban)
Czech (czech)
Delis (delis)
Diners (diners)
Dinner Theater (dinnertheater)
Ethiopian (ethiopian)
Fast Food (hotdogs)
Filipino (filipino)
Fish & Chips (fishnchips)
Fondue (fondue)
Food Court (food_court)
Food Stands (foodstands)
French (french)
Mauritius (mauritius)
Reunion (reunion)
Game Meat (gamemeat)
Gastropubs (gastropubs)
Georgian (georgian)
German (german)
Gluten-Free (gluten_free)
Greek (greek)
Guamanian (guamanian)
Halal (halal)
Hawaiian (hawaiian)
Himalayan/Nepalese (himalayan)
Honduran (honduran)
Hong Kong Style Cafe (hkcafe)
Hot Dogs (hotdog)
Hot Pot (hotpot)
Hungarian (hungarian)
Iberian (iberian)
Indian (indpak)
Indonesian (indonesian)
Irish (irish)
Italian (italian)
Calabrian (calabrian)
Sardinian (sardinian)
Sicilian (sicilian)
Tuscan (tuscan)
Japanese (japanese)
Conveyor Belt Sushi (conveyorsushi)
Izakaya (izakaya)
Japanese Curry (japacurry)
Ramen (ramen)
Teppanyaki (teppanyaki)
Kebab (kebab)
Korean (korean)
Kosher (kosher)
Laotian (laotian)
Latin American (latin)
Colombian (colombian)
Salvadoran (salvadoran)
Venezuelan (venezuelan)
Live/Raw Food (raw_food)
Malaysian (malaysian)
Mediterranean (mediterranean)
Falafel (falafel)
Mexican (mexican)
Tacos (tacos)
Middle Eastern (mideastern)
Egyptian (egyptian)
Lebanese (lebanese)
Modern European (modern_european)
Mongolian (mongolian)
Moroccan (moroccan)
New Mexican Cuisine (newmexican)
Nicaraguan (nicaraguan)
Noodles (noodles)
Pakistani (pakistani)
Pan Asian (panasian)
Persian/Iranian (persian)
Peruvian (peruvian)
Pizza (pizza)
Polish (polish)
Polynesian (polynesian)
Pop-Up Restaurants (popuprestaurants)
Portuguese (portuguese)
Poutineries (poutineries)
Russian (russian)
Salad (salad)
Sandwiches (sandwiches)
Scandinavian (scandinavian)
Scottish (scottish)
Seafood (seafood)
Singaporean (singaporean)
Slovakian (slovakian)
Soul Food (soulfood)
Soup (soup)
Southern (southern)
Spanish (spanish)
Sri Lankan (srilankan)
Steakhouses (steak)
Supper Clubs (supperclubs)
Sushi Bars (sushi)
Syrian (syrian)
Taiwanese (taiwanese)
Tapas Bars (tapas)
Tapas/Small Plates (tapasmallplates)
Tex-Mex (tex-mex)
Thai (thai)
Turkish (turkish)
Ukrainian (ukrainian)
Uzbek (uzbek)
Vegan (vegan)
Vegetarian (vegetarian)
Vietnamese (vietnamese)
Waffles (waffles)
Wraps (wraps)
Shopping (shopping)
Adult (adult)
Antiques (antiques)
Art Galleries (galleries)
Arts & Crafts (artsandcrafts)
Art Supplies (artsupplies)
Cards & Stationery (stationery)
Cooking Classes (cookingclasses)
Costumes (costumes)
Embroidery & Crochet (embroideryandcrochet)
Fabric Stores (fabricstores)
Framing (framing)
Paint-Your-Own Pottery (paintyourownpottery)
Auction Houses (auctionhouses)
Baby Gear & Furniture (baby_gear)
Battery Stores (batterystores)
Bespoke Clothing (bespoke)
Books, Mags, Music & Video (media)
Bookstores (bookstores)
Comic Books (comicbooks)
Music & DVDs (musicvideo)
Newspapers & Magazines (mags)
Video Game Stores (videogamestores)
Videos & Video Game Rental (videoandgames)
Vinyl Records (vinyl_records)
Brewing Supplies (brewingsupplies)
Bridal (bridal)
Cannabis Dispensaries (cannabisdispensaries)
Computers (computers)
Cosmetics & Beauty Supply (cosmetics)
Customized Merchandise (custommerchandise)
Department Stores (deptstores)
Discount Store (discountstore)
Drones (drones)
Drugstores (drugstores)
Duty-Free Shops (dutyfreeshops)
Electronics (electronics)
Eyewear & Opticians (opticians)
Sunglasses (sunglasses)
Farming Equipment (farmingequipment)
Fashion (fashion)
Accessories (accessories)
Ceremonial Clothing (ceremonialclothing)
Children's Clothing (childcloth)
Clothing Rental (clothingrental)
Department Stores (deptstores)
Formal Wear (formalwear)
Fur Clothing (furclothing)
Hats (hats)
Leather Goods (leather)
Lingerie (lingerie)
Maternity Wear (maternity)
Men's Clothing (menscloth)
Plus Size Fashion (plus_size_fashion)
Shoe Stores (shoes)
Sports Wear (sportswear)
Dance Wear (dancewear)
Surf Shop (surfshop)
Swimwear (swimwear)
Traditional Clothing (tradclothing)
Used, Vintage & Consignment (vintage)
Women's Clothing (womenscloth)
Fireworks (fireworks)
Fitness/Exercise Equipment (fitnessequipment)
Flea Markets (fleamarkets)
Flowers & Gifts (flowers)
Cards & Stationery (stationery)
Florists (florists)
Gift Shops (giftshops)
Gemstones & Minerals (gemstonesandminerals)
Gold Buyers (goldbuyers)
Guns & Ammo (guns_and_ammo)
Head Shops (headshops)
High Fidelity Audio Equipment (hifi)
Hobby Shops (hobbyshops)
Home & Garden (homeandgarden)
Appliances (appliances)
Candle Stores (candlestores)
Christmas Trees (christmastrees)
Furniture Stores (furniture)
Grilling Equipment (grillingequipment)
Hardware Stores (hardware)
Holiday Decorations (holidaydecorations)
Home Decor (homedecor)
Hot Tub & Pool (hottubandpool)
Kitchen & Bath (kitchenandbath)
Kitchen Supplies (kitchensupplies)
Lighting Stores (lightingstores)
Mattresses (mattresses)
Nurseries & Gardening (gardening)
Hydroponics (hydroponics)
Outdoor Furniture Stores (outdoorfurniture)
Paint Stores (paintstores)
Playsets (playsets)
Pumpkin Patches (pumpkinpatches)
Rugs (rugs)
Tableware (tableware)
Horse Equipment Shops (horsequipment)
Jewelry (jewelry)
Knitting Supplies (knittingsupplies)
Livestock Feed & Supply (livestocksupply)
Luggage (luggage)
Medical Supplies (medicalsupplies)
Military Surplus (militarysurplus)
Mobile Phone Accessories (cellphoneaccessories)
Mobile Phones (mobilephones)
Motorcycle Gear (motorcyclinggear)
Musical Instruments & Teachers (musicalinstrumentsandteachers)
Office Equipment (officeequipment)
Outlet Stores (outlet_stores)
Packing Supplies (packingsupplies)
Pawn Shops (pawn)
Perfume (perfume)
Personal Shopping (personal_shopping)
Photography Stores & Services (photographystores)
Pool & Billiards (poolbilliards)
Pop-up Shops (popupshops)
Props (props)
Public Markets (publicmarkets)
Religious Items (religiousitems)
Safe Stores (safestores)
Safety Equipment (safetyequipment)
Shopping Centers (shoppingcenters)
Souvenir Shops (souvenirs)
Spiritual Shop (spiritual_shop)
Sporting Goods (sportgoods)
Bikes (bikes)
Dive Shops (diveshops)
Golf Equipment (golfequipment)
Hockey Equipment (hockeyequipment)
Hunting & Fishing Supplies (huntingfishingsupplies)
Outdoor Gear (outdoorgear)
Skate Shops (skateshops)
Ski & Snowboard Shops (skishops)
Sports Wear (sportswear)
Dance Wear (dancewear)
Tabletop Games (tabletopgames)
Teacher Supplies (teachersupplies)
Thrift Stores (thrift_stores)
Tobacco Shops (tobaccoshops)
Toy Stores (toys)
Trophy Shops (trophyshops)
Uniforms (uniforms)
Used Bookstore (usedbooks)
Vape Shops (vapeshops)
Vitamins & Supplements (vitaminssupplements)
Watches (watches)
Wholesale Stores (wholesale_stores)
Wigs"

# categories = categories.split(/ \(.+?\)\s/).uniq
#
# Category.destroy_all
# categories.each do |category|
#   Category.create!(name: category)
# end

u1 = User.create(email: "a@gmail.com", first_name: "Anthony", last_name: "Hopkins", password: "starwars", zip_code: "12340")
u2 = User.create(email: "b@gmail.com", first_name: "John", last_name: "Doe", password: "starwars", zip_code: "12340")
u3 = User.create(email: "c@gmail.com", first_name: "Oliver", last_name: "Baller", password: "starwars", zip_code: "12340")
u4 = User.create(email: "d@gmail.com", first_name: "Jimmy", last_name: "Carr", password: "starwars", zip_code: "12340")
u5 = User.create(email: "e@gmail.com", first_name: "Christina", last_name: "Aguilera", password: "starwars", zip_code: "12340")
u6 = User.create(email: "f@gmail.com", first_name: "Pharel", last_name: "Williams", password: "starwars", zip_code: "12340")

b1 = Business.create(name: "App Academy NYC", neighborhood: "Midtown West", street_address: "22 W 38th St", city: "New York", state: "NY", zip: "10018", website: "appacademy.io", latitude: 40.751282, longitude: -73.98399)
b2 = Business.create(name: "Hack Reactor", neighborhood: "South Village", street_address: "315 Hudson St", city: "New York", state: "NY", zip: "10013", phone: "(212) 709-4613", website: "hackreactor.com/new-york-city-campus", latitude: 40.726302, longitude: -74.00807)
b3 = Business.create(name: "Zoma", neighborhood: "Harlem", street_address: "2084 Frederick Douglass Blvd", city: "New York", state: "NY", zip: "10026", phone: "(212) 964-8365", website: "zomanyc.com", price: "$$",latitude: 40.802282, longitude: -73.956578)
b4 = Business.create(name: "Hop Kee", neighborhood: "Chinatown, Civic Center", street_address: "21 Mott St", city: "New York", state: "NY", zip: "10013", phone: "(212) 964-8365" , website: "hop-kee-nyc.com", price: '$$',latitude: 40.714452, longitude: -73.998891)
b5 = Business.create(name: "BCD Tofu House", neighborhood: "Bayside", street_address: "220-05 Northern Blvd", city: "Bayside", state: "NY", zip: "11361", phone: "(718) 224-8889", website: "bcdtofu.com", price: "$$" ,latitude:  40.761679, longitude: -73.761696)
b6 = Business.create(name: "Bodee Construction LLC", neighborhood: "Contractors", street_address: "96 Linwood Plz", city: "Fort Lee", state: "NJ", zip: "10018", phone: "(201) 741-7870", website: "bodeeconstruction.com", latitude: 40.860615, longitude: -73.971446)

bh1 = BusinessHour.create(business_id: b1.id, day: "Sun", hours: "Closed")
bh2 = BusinessHour.create(business_id: b1.id, day: "Mon", hours: "9:00 am - 6:00 pm")
bh3 = BusinessHour.create(business_id: b1.id, day: "Tue", hours: "9:00 am - 6:00 pm")
bh4 = BusinessHour.create(business_id: b1.id, day: "Wed", hours: "9:00 am - 6:00 pm")
bh5 = BusinessHour.create(business_id: b1.id, day: "Thu", hours: "9:00 am - 6:00 pm")
bh6 = BusinessHour.create(business_id: b1.id, day: "Fri", hours: "9:00 am - 6:00 pm")
bh7 = BusinessHour.create(business_id: b1.id, day: "Sat", hours: "Closed")

bh8 = BusinessHour.create(business_id: b2.id, day: "Sun", hours: "Closed")
bh9 = BusinessHour.create(business_id: b2.id, day: "Mon", hours: "9:00 am - 8:00 pm")
bh10 = BusinessHour.create(business_id: b2.id, day: "Tue", hours: "9:00 am - 8:00 pm")
bh11 = BusinessHour.create(business_id: b2.id, day: "Wed", hours: "9:00 am - 8:00 pm")
bh12 = BusinessHour.create(business_id: b2.id, day: "Thu", hours: "9:00 am - 8:00 pm")
bh13 = BusinessHour.create(business_id: b2.id, day: "Fri", hours: "9:00 am - 8:00 pm")
bh14 = BusinessHour.create(business_id: b2.id, day: "Sat", hours: "9:00 am - 8:00 pm")

bh15 = BusinessHour.create(business_id: b3.id, day: "Sun", hours: "12:00 pm - 11:00 pm")
bh16 = BusinessHour.create(business_id: b3.id, day: "Mon", hours: "5:00 pm - 11:00 pm")
bh17 = BusinessHour.create(business_id: b3.id, day: "Tue", hours: "5:00 pm - 11:00 pm")
bh18 = BusinessHour.create(business_id: b3.id, day: "Wed", hours: "5:00 pm - 11:00 pm")
bh19 = BusinessHour.create(business_id: b3.id, day: "Thu", hours: "5:00 pm - 11:00 pm")
bh20 = BusinessHour.create(business_id: b3.id, day: "Fri", hours: "5:00 pm - 11:00 pm")
bh21 = BusinessHour.create(business_id: b3.id, day: "Sat", hours: "12:00 pm - 11:00 pm")

bh22 = BusinessHour.create(business_id: b4.id, day: "Sun", hours: "11:00 am - 1:00 am")
bh23 = BusinessHour.create(business_id: b4.id, day: "Mon", hours: "11:00 am - 1:00 am")
bh24 = BusinessHour.create(business_id: b4.id, day: "Tue", hours: "11:00 am - 1:00 am")
bh25 = BusinessHour.create(business_id: b4.id, day: "Wed", hours: "11:00 am - 1:00 am")
bh26 = BusinessHour.create(business_id: b4.id, day: "Thu", hours: "11:00 am - 1:00 am")
bh27 = BusinessHour.create(business_id: b4.id, day: "Fri", hours: "11:00 am - 4:00 am")
bh28 = BusinessHour.create(business_id: b4.id, day: "Sat", hours: "11:00 am - 4:00 am")

bh29 = BusinessHour.create(business_id: b5.id, day: "Sun", hours: "10:30 am - 10:30 pm")
bh30 = BusinessHour.create(business_id: b5.id, day: "Mon", hours: "10:30 am - 10:30 pm")
bh31 = BusinessHour.create(business_id: b5.id, day: "Tue", hours: "10:30 am - 10:30 pm")
bh32 = BusinessHour.create(business_id: b5.id, day: "Wed", hours: "10:30 am - 10:30 pm")
bh33 = BusinessHour.create(business_id: b5.id, day: "Thu", hours: "10:30 am - 10:30 pm")
bh34 = BusinessHour.create(business_id: b5.id, day: "Fri", hours: "10:30 am - 10:30 pm")
bh35 = BusinessHour.create(business_id: b5.id, day: "Sat", hours: "10:30 am - 10:30 pm")

bh36 = BusinessHour.create(business_id: b6.id, day: "Sun", hours: "Closed")
bh37 = BusinessHour.create(business_id: b6.id, day: "Mon", hours: "8:00 am - 6:00 pm")
bh38 = BusinessHour.create(business_id: b6.id, day: "Tue", hours: "8:00 am - 6:00 pm")
bh39 = BusinessHour.create(business_id: b6.id, day: "Wed", hours: "8:00 am - 6:00 pm")
bh40 = BusinessHour.create(business_id: b6.id, day: "Thu", hours: "8:00 am - 6:00 pm")
bh41 = BusinessHour.create(business_id: b6.id, day: "Fri", hours: "8:00 am - 5:00 pm")
bh42 = BusinessHour.create(business_id: b6.id, day: "Sat", hours: "Closed")

bc1 = BusinessCategory.create(business_id: b1.id, category_id: Category.where("name SIMILAR TO 'Vocational &%'").first.id)
bc2 = BusinessCategory.create(business_id: b2.id, category_id: Category.where("name SIMILAR TO 'Vocational &%'").first.id)
bc3 = BusinessCategory.create(business_id: b3.id, category_id: Category.where("name = 'Ethiopian'").first.id)
bc4 = BusinessCategory.create(business_id: b4.id, category_id: Category.where("name = 'Seafood'").first.id)
bc5 = BusinessCategory.create(business_id: b4.id, category_id: Category.where("name = 'Cantonese'").first.id)
bc6 = BusinessCategory.create(business_id: b5.id, category_id: Category.where("name = 'Korean'").first.id)
bc7 = BusinessCategory.create(business_id: b6.id, category_id: Category.where("name SIMILAR TO 'Contractor%'").first.id)

r1 = Review.create(body: "I actually got a job after completing App Academy's in-person full-time curriculum in NYC.  I wanted to wait until I actually got an offer, so here it is.

If you're looking at this review, you're probably looking to make a career-change or gain an edge in landing that first software development role after graduating University (or High School?).  For me, it was absolutely worth it.

1. This is one of the only coding bootcamps which hold you to a certain learning-pace with weekly assessments for the first 8-ish weeks.  If you fall behind and fail two of them, you're out of the program, and trust me this will take a lot of work to pass.  It ensures that you actually learned the material and can do the basics, but the pace of this program isn't for everyone.  You will wake up in the morning, get to the office, code all day, go home, work on HW assignments, code some more, sleep, then repeat for 3 months.  You will literally live/eat/breathe code for the duration and you'll learn so much, but this brings up my second point.

2. You will have no life during the program.  When people say this in the reviews, they're not being excessive.  I almost had a panic attack on the night before my first assessment (Sunday) because I was struggling with some concepts.  You will learn a new concept and then be expected to pass an assessment on it the following week, while already learning new material.  Tell your friends/girlfriend/family/dog that you'll pay attention to them after 3 months.  (For reference, my cohort had like 20% of the cohort drop out...  This isn't a joke)

3. You will meet some of the most brilliant people you've ever met in your cohort.  We've had Ivy-League grads, WallStreet guys, Entrepreneurs, Musicians, Basement gamers who want to finally get a job, etc...  They were from all different backgrounds, but almost every single one of them were brilliant in their own way.  I actually felt dumb for the first time in my life.  Being surrounded by these people and pair-programming with each of them every single day will help you learn and see code in a different way.  You'll also learn how to deal with not-so-favorable people, which will help you during your actual job (stubborn/argumentative people, keyboard hogs, etc), but these interactions are rare.

4. The Job-Search support is actually one of the best parts of this curriculum.  Technical and Non-Technical interviewing is a skill just like programming, and you'll gain a ton of practice white boarding and talking about yourself/background.  My career coach was the best hype-man I could've ever asked for, and I think he actually helped me ultimately land my first role.

If you put in the work, you'll land a job.  A vast majority of my cohort all landed jobs within the first 6-months after program completion.
The most important part is putting in the work after you actually finish the program (Job-Search is honestly the hardest part because there's minimal hand holding and you're actually competing for roles against other people who often have CS degrees).  There's no time for an extended break after completing the program.  Start working on more features on your fullstack project, start learning data structures / algorithms more in depth, white board at least once a week, etc...  It will take a lot of work.  The best part is that you have access to the office at all times, so you can go in to work while you look for a job even after you complete the program.

For me, this program changed my life and I'm thankful I went through it.

Lastly, I want to share one tip:  Before you start the program, you absolutely should complete a beginner's web-development \"course\" on freecodecamp or Udemy.  It goes a LONG way, trust me.", user_id: u1.id, business_id: b1.id, score: 5, date: "11/20/2018")
r2 = Review.create(body: "I'm writing this as a review of the JumpStart program. Even though I didn't end up going to App Academy (full disclosure: I was rejected), I am so grateful for my brief time at JumpStart.

I applied to a/A because one of my friends went here 4 years ago after a life in finance and said it the best decision he ever made. I had taken online coding courses where I was basically copying and pasting code to make cute webpages and apps without much functionality, and his story inspired me to turn my life around too! Ha Ha. Not that easy. After filling out a brief application, I was contacted to participate in JumpStart which is their free 2 week mini-bootcamp type course. Not to be confused with their actual bootcamp prep course, which is something ridic like $3,000. All the material was presented online, and I participated in the evening courses from 6-9 every weeknight for 2 weeks.

I want to say going in person was not that necessary since all the material is presented in the online videos. The main benefit is that you have TAs for direct questions and you get to practice pair programming which is an integral process in bootcamp, and job interviews. They took attendance every day, though I'm not really sure what for.

Another benefit of JumpStart is you get to bypass the coding challenge and go straight to the interview. That basically means you get to interview 3 weeks into learning how to code. Ha. j/k. Some people in the class actually did know how to code.

Those 2 weeks were my introduction to the algorithmic type programming questions they give you in bootcamp interviews, and Jumpstart claims it provides you with all the information you need to pass the interview. While that may be true, 2 weeks is DEFINITELY not enough time to get you ramped up to get into a competitive coding bootcamp. I didn't think the material was too crazy since my math isn't terrible, but I could have definitely used another few weeks of practicing problems on CodeWars before my interview. You want to be at the point where you're like \"ok yeah def know how to solve this because i've done it a hundred times before\" because you're not allowed to run code during your interview and you have to talk through your entire process without seeing the console errors. I was also given a problem that included recursion in my interview, and I did not know what that was before my interview. My interviewer was very nice though, and JumpStarters get a second chance to interview through the traditional application process.

I didn't end up re-interviewing at a/A because their next cohort was a 4 months away and I was looking to make a change before work got busy again. For anyone considering doing their mini course it's a great way to start without doing it on your own! They provided so many practice problems during that short period with amazing instructional walkthroughs. I felt it was because I did JumpStart I was able to do well on my coding interview with another program a few weeks after.", user_id: u2.id, business_id: b1.id, score: 4, date: "10/1/2018")

r3 = Review.create(body: "App Academy was definitely the hardest 3 months of my life. At times it was a bit brutal, with 10% of our cohort getting kicked out before the end of the program. The program is certainly not for everyone, but if you are a fast learner AND can dedicate pretty much your entire life to the program, you can get a job as a Software Engineer after this program.

You certainly are expected to work as much as you everyday. Everyone is incredibly smart and motivated; I went to a top school in the United States, but found my peers here to be heads and tails above my university peers.

That being said, they do deliberately pace the course so that you can keep up -- pushing you to the brink and then giving you a few days for the material to sink in. I was also able to take a small handful of days off, but some are unable to do so.

I had absolutely NO computer science background before attending, and ended up getting a job within the first month following the program, so this program DEFINITELY fulfills its promises.", user_id: u3.id, business_id: b1.id, score: 5, date: "1/16/2018")

r4 = Review.create(body: "Just finished the curriculum part of App Academy. It was intense, grueling, and sleep-deprived, but I would do it all over again. I have learned so much and went from being an absolute beginner with no coding experience whatsoever to where I can call myself an software engineer (still have so much to learn though lol). They have a great and intense curriculum (it has to be that way for you to go from 0-100 real quick), and they have a great and talented staff of teachers that will lead, mold, consult, and be there with you every step of the way. They are smart people, people. You  in good hands.

If you are someone who wants to change the direction of your life or want to get into programming for whatever reason, AND above all else is willing to put in the hours to do it, do not hesitate and go for it. You won't regret it.

You will learn ruby, rails, JavaScript, react, css", user_id: u4.id, business_id: b1.id, score: 5, date: "5/19/2018")

i1 = Image.create!(image_url: "https://s3-media3.fl.yelpcdn.com/bphoto/X2RwIiwSmvwXGVlg7heH7w/o.jpg", comment: "Graduating cohort (06/16)", user_id: u1.id, business_id: b1.id)
i2 = Image.create!(image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/I7BXjaEuPTg0ep50RgP5eA/o.jpg", comment: "Graduating cohort (08/16)", user_id: u1.id, business_id: b1.id)
i3 = Image.create!(image_url: "https://s3-media2.fl.yelpcdn.com/bphoto/u3RjQ0E6K8viHxse8qkKjw/o.jpg", comment: "Soho office (06/16)", user_id: u2.id, business_id: b1.id)
i4 = Image.create!(image_url: "https://s3-media3.fl.yelpcdn.com/bphoto/6ARXnljJb1g7brn0e7gT-Q/o.jpg", comment: "Graduation day!", user_id: u3.id, business_id: b1.id, review_id: r1.id)
i5 = Image.create!(image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/ysihvWX-XfjnIQ3Fyh8K1g/o.jpg", user_id: u1.id, business_id: b1.id)
i6 = Image.create!(image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/tHZxg9CovWRGsT-ci_uLmQ/o.jpg", user_id: u4.id, business_id: b2.id)
